In [2]:
import numpy as np
import scipy.linalg as lg

In [3]:
def H(m, n, g):

    fac = g/16.0
    if m-n == 4:
        return fac * np.sqrt((n+1)*(n+2)*(n+3)*(n+4))
    elif m-n == 2:
        return fac * 2 * (3 + 2*n) * np.sqrt((n+1)*(n+2))
    elif m == n:
        return fac * (3+6*n+6*n**2)+n+0.5
    elif m-n == -2:
        return fac*2*(2*n-1)*np.sqrt(n*(n-1))
    elif m-n == -4:
        return fac*np.sqrt(n*(n-1)*(n-2)*(n-3))
    else:
        return 0

In [4]:
def es(g, N):
    mt = np.matrix([[H(m, n, g) for m in range(N)] for n in range(N)])
    return lg.eigvalsh(mt)

In [5]:
def mat(g, N):
    mt = np.matrix([[H(m, n, g) for m in range(N)] for n in range(N)])
    return mt

In [109]:
Er0 = es(0, 10)

In [110]:
Er0

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [111]:
E0, V0 = lg.eig(mat(0, 10))

In [112]:
E0

array([0.5+0.j, 1.5+0.j, 2.5+0.j, 3.5+0.j, 4.5+0.j, 5.5+0.j, 6.5+0.j,
       7.5+0.j, 8.5+0.j, 9.5+0.j])

In [201]:
E , V = lg.eig(mat(2,10))

In [202]:
Er = es(2, 10)

In [203]:
Er

array([  0.69668553,   2.3264345 ,   4.3448319 ,   6.72704067,
        10.87101595,  15.74576257,  29.61416732,  40.54948324,
        83.8482993 , 106.52627902])

In [204]:
E

array([ 83.8482993 +0.j,  29.61416732+0.j,   0.69668553+0.j,
         4.3448319 +0.j,  10.87101595+0.j, 106.52627902+0.j,
        40.54948324+0.j,  15.74576257+0.j,   2.3264345 +0.j,
         6.72704067+0.j])

In [205]:
c = []
for i in range(10):
    c.append(np.dot(V[2],V0[i]))

In [206]:
c

[0.03331425068958794,
 0.23110477552040062,
 0.17762765271898392,
 -0.8076531641080931,
 -0.5114934280402696,
 1.238105170571936e-17,
 -3.489441844109051e-17,
 -6.02042032424576e-17,
 -1.9398544964846233e-16,
 -5.037132869186648e-16]

In [207]:
c = np.array(c)

In [208]:
for i in range(len(c)):
    c[i] = ((1/math.factorial(i))) * c[i]

In [209]:
c

array([ 3.33142507e-02,  2.31104776e-01,  8.88138264e-02, -1.34608861e-01,
       -2.13122262e-02,  1.03175431e-19, -4.84644701e-20, -1.19452784e-20,
       -4.81114706e-21, -1.38809878e-21])

In [32]:
from sympy import diff, sin, exp 
import math

In [33]:
from sympy.abc import x

In [43]:
L = []

In [44]:
L.append(exp(-x**2))

In [45]:
L.append(x * L[0] - diff(L[0], x))

In [49]:
i = 1
while(i<30):
    L.append(x * L[i] - diff(L[i], x))
    i = i + 1  

KeyboardInterrupt: 

In [123]:
with open("diff0.txt", "w") as output:
    output.write(str(L[0:10]))


In [124]:
S = np.array(L[0:10])

In [125]:
len(S)

10

In [210]:
M = np.dot(S,c)

In [141]:
with open("diff0.txt", "w") as output:
    output.write(str(M))


In [105]:
from sympy.plotting import plot